basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(), name='delete'),
]

cbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('', views.index, name='index'),
    # grab that class and show it as a view
    path('cbv', views.CBView.as_view()),
    path('cbv_index', views.IndexView.as_view()),
]

basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    # instructions set for submit button from school_form.html
    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.name

basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
# a eneric type of class based view
from django.views.generic import (View, TemplateView, ListView, DetailView, 
                                    CreateView, UpdateView, DeleteView)
from django.http import HttpResponse
from basic_app import models
# Create your views here.

def index(request):
    my_dictionary = {'value': 'new_value'}
    return render(request, 'index.html', context=my_dictionary)

class CBView(View):
    def get(self, request):
        return HttpResponse("Class based view, first use!")

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['value'] = 'value for context'
        context['up_value'] = 'updated value for context'
        return context

class SchoolListView(ListView):
    # when no context_object_name is set, ListView by default, passes an object by the 
    # name of lowercase model name '_' list(school_list in this case)
    # for DetailView, the name is lowercase value of model name
    model = models.School
    template_name = 'basic_app/school_list.html'

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    model = models.School
    # without adding fields, we get an ImproperlyConfigured error
    fields = ('name', 'principal', 'location')


class SchoolUpdateView(UpdateView):
    model = models.School
    fields = ('name', 'principal')


class SchoolDeleteView(DeleteView):
    model = models.School
    # once the school has been deleted, go back to this page
    # we use reverse_lazy as we only want this to be called as deletion is successful
    success_url = reverse_lazy("basic_app:list")

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Base</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
                <li><a class="navbar-link" href=" {% url 'admin:index' %}">Admin</a></li>
            </nav>
            </ul>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>        
    </body>
</html>

basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<h1>Delete {{ school.name }}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the school detail page</h1>
    <h2>School details:</h2>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <p>Location: {{ school_detail.location }}</p>
    <h3>Students:</h3>
    {% for student in school_detail.students.all %}
        <p>{{ student.name }} who is {{ student.age }} years old.</p>    
    {% endfor %}
</div>

<div class="container">
    <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>
{% endblock %}

basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<h1>
    <!-- if primary key does not exist, create  -->
    {% if not form.instance.pk %}
    Create School

    <!-- if it does, update -->
    {% else %}
    Update School
    {% endif %}
</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>
{% endblock %}

basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
    <h1>Welcome to a list of all the schools</h1>
    {% for school in school_list %}
        <!-- here, href os pnly going to return a single integer value -->
        <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
    {% endfor %}
{% endblock %}

<a href=""

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Base</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="#"></a>Schools</li>
                <li><a class="navbar-link" href="#">Admin</a></li>             
            </nav>
            </ul>
        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>        
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <h1>Hello, Index Page</h1>
    {{ value }} </br>
    {{ up_value }}
{% endblock %}